### ISSUE TITLE
Arabic Sentiment Analysis

### ISSUE THREAD

**Issue by sheikho1983** [ali7amdi/Python-Programming-Course#1]
Hello,

Would you please to help me hiw can I use this code for Sentiment Analysis of Facebook Post that in Arabic especially Syrian Dialect?

Thanx very much for your cooperation

**Comment by ali7amdi** [comment]
Hi, Please refer to lesson #31. Its an example of Arabic data. 

https://github.com/ali7amdi/Python-for-Data-Science-Course/blob/master/31%20Python%20Sklearn%20Text-classificatin%20-%20sentment%20analysis.ipynb
